[package]
name = "sparkle-convenience"
version = "0.14.26"
authors = ["lara <laralove143@icloud.com>"]
edition = "2021"
description = "A wrapper over Twilight designed to make it more convenient to use"
repository = "https://github.com/laralove143/sparkle-convenience/"
license = "ISC"
keywords = ["discord", "discord-api", "twilight"]
categories = ["api-bindings", "asynchronous", "caching"]

[dependencies]
tokio = { version = "1.21", features = ["rt-multi-thread"] }
anyhow = "1.0"
async-trait = "0.1"
titlecase = "2.2"
twilight-http = "0.14"
twilight-gateway = "0.14"
twilight-model = "0.14"
twilight-validate = "0.14"

[dev-dependencies]
tokio = { version = "1.21", features = ["macros"] }
futures = "0.3"